version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - USE_MOCK=true
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:8501
    env_file:
      - .env
    volumes:
      - ./exports:/app/exports
      - ./captures:/app/captures
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  exports:
  captures:
